apiVersion: v1
kind: Namespace
metadata:
  name: webapppy-flux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-1-deploy
  namespace: webapppy-flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test-1
  template:
    metadata:
      labels:
        app: app-test-1
    spec:
      containers:
      - name: app-test-1
        image: skoopy365/webapp-py:1.0.13 # {"$imagepolicy": "flux-system:webapppy-imagepolicy"}
        ports:
        - name: web
          containerPort: 8000
        resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-1-svc
  namespace: webapppy-flux
  labels:
    app: app-test-1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: app-test-1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-test-1-ingress
  namespace: webapppy-flux
  annotations:
    cert-manager.io/issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - webapppy-flux.lukflk.nl
      secretName: wildcard-lukflk
  rules:
    - host: webapppy-flux.lukflk.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-test-1-svc
                port:
                  number: 8000
