---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: webapppy-imagepolicy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: webapppy-imagerepository
    namespace: flux-system
  policy:
    semver:
      range: '>=1.0.0'