---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: webapppy-ImagePolicy
  namespace: webapppy-flux
status:
  latestImage: skoopy365/webapp-py
  interval: 1m 
  provider: generic